export const categories = [
  {
    id: 1,
    img: "",
    title: "Yoghurt",
    cat: "yoghurt",
  },
  {
    id: 2,
    img: "",
    title: "Milk",
    cat: "milk",
  },
  {
    id: 3,
    img: "",
    title: "Creams",
    cat: "cream",
  },
  {
    id: 4,
    img: "",
    title: "Butter",
    cat: "butter",
  },
  {
    id: 5,
    img: "",
    title: "Cheese",
    cat: "cheese",
  },
  {
    id: 6,
    img: "",
    title: "Ma Cuisine",
    cat: "ma-cuisine",
  },
];

export const products = [
  {
    _id: 1,
    category: "yoghurt",
    sub_category: "tinga tinga",
    title: "Tinga Tinga Yoghurt",
    desc: "some fairly long description",
    img: "",
  },
  {
    _id: 2,
    category: "yoghurt",
    sub_category: "greek",
    title: "Greek Yoghurt",
    desc: "some fairly long description",
    img: "",
  },
  {
    _id: 3,
    category: "milk",
    sub_category: "fresh",
    title: "Bio 1L",
    desc: "some fairly long description",
    img: "",
  },
  {
    _id: 11,
    category: "milk",
    sub_category: "fresh",
    title: "Bio 1L",
    desc: "some fairly long description",
    img: "",
  },
  {
    _id: 12,
    category: "milk",
    sub_category: "fresh",
    title: "Bio 1L",
    desc: "some fairly long description",
    img: "",
  },
  {
    _id: 4,
    category: "milk",
    sub_category: "long life",
    title: "Bio 1L",
    desc: "some fairly long description",
    img: "",
  },
  {
    _id: 5,
    category: "cheese",
    sub_category: "soft cheese",
    title: "Ricotta",
    desc: "some fairly long description",
    img: "",
  },
  {
    _id: 6,
    category: "cheese",
    sub_category: "hard cheese",
    title: "Cheddar",
    desc: "some fairly long description",
    img: "",
  },
  {
    _id: 7,
    category: "butter",
    sub_category: "",
    title: "salted butter",
    desc: "some fairly long description",
    img: "",
  },
  {
    _id: 8,
    category: "butter",
    sub_category: "",
    title: "margarine",
    desc: "some fairly long description",
    img: "",
  },
];
